name: "Bug Report"
description: "Report a bug or unexpected behavior"
labels: ["type: bug"]
title: "bug: [DESCRIPTION]"

body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is and what you expected to happen"

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: |
        Please list steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error

  - type: textarea
    attributes:
      label: "Screenshots / Logs"
      description: |
        If applicable, add screenshots or logs to help explain your problem

  - type: dropdown
    attributes:
      label: "Operating System"
      options:
        - Windows
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux / Ubuntu
        - Other

  - type: input
    attributes:
      label: "Version"
      description: "What version are you running?"
      placeholder: "e.g., v1.0.0"

  - type: input
    attributes:
      label: "Additional Context"
      description: "Any other context about the problem (hardware specs, related issues, etc.)"
