name: "Feature Request"
description: "Suggest an idea or new feature"
labels: ["type: feature"]
title: "feat: [DESCRIPTION]"

body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Problem Statement"
      description: "Describe the problem you're facing or the use case"
      placeholder: |
        I'm always frustrated when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Proposed Solution"
      description: "Describe what you'd like to happen. Examples are welcome!"

  - type: textarea
    attributes:
      label: "Alternatives Considered"
      description: "Describe any alternative solutions or features you've considered"

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context, mockups, or screenshots about the feature request"
